function myFunction () {
    document.getElementById("myDropdown")
}

genText.addEventListener("click", function() {
  let messages = [
    "Wishing you the absolute best on your b-day!",
    "Happy birthday!",
    "Cheers to more fun, more memories, and more cake!",
    "I cant think of a better gift than doing this for u",
    "I love you", 
    "Cheers to another trip around the sun! Keep on shining, beh",
    "Youre the brightest star today! Happy birthday!",
    "Cheers to your own personal new year",
    "I adore you",
    "Enjoy your special day to the fullest!",
    "Wishing you a fantastic birthday and a wonderful year ahead",
    "I cant wait to be with you",
    "I hope we see each other soon",
    "I hope all your wishes come true!",
    "You are an amazing person",
    "Im proud of you",
    "Thank you for existing",
    "Wishing you nothing but love and happiness on your special day!",
    "Pi bday future Architect!",
    "You inspire me a lot",
    "Heres to more life, love, and adventures along the way!",
    "Sana hindi ka ma cringe rito hahaha",
    "You deserve all the good things in life!",
    "You will always have me",
    "Im always here to support you!",
    "Don't think of it as aging, think of it as becoming a classic!",
    "Cheers to more fun times together. Best wishes on your birthday!",
    "When we met, I knew that youd always be a part of my life. Happy birthday!",
    "Keep reaching your goal!",
    "I have a gift for you",
    "San ka punta? To the moon, roadtrip, broom broom",
    "No regrets, just love",
    "You brighten my life, and I am so grateful to have you by my side. Happy birthday!",
    "To me, you are perfect",
    "You are one of my greatest blessing",
    "Cute ni nyah",
    "Hello sana masaya ka ngayong bday mo",
    "Ingat ka palagi",
    "Pogi ni JK",
    "Go and save the Earth",
    "Time to party like its your birthday! joke",
    "You bring so much joy into my life. Happy birthday!",
    "Wishing you the best birthday yet!",
    "You are so special. Every day should be your birthday.",
    "The more days go, the more I fall in love with you.",
    "Happy cake day!",
    "Korni ba i2?",
    "I wanted to wish you the very best on your birthday, but you already have me. (char lang)",
    "Happy birthday to one of the smartest woman I know.",
    "Im loving you more each and every day.",
    "May God continue to cover you on your special day and beyond.",
    "My love for you isnt something that can be measured. I just know my heart is full of it.",
    "As you turn another year older, I know that God will continue to bless you.",
    "I am always including you with my prayers. Wishing you the best birthday yet! I love you, baby.",
    "gg sana masaya ka sa bday mo lods",
    "pakain naman dyan",
    "sana one day isang araw makapag balot ako ng shanghai galing sa bday mo",
    "Ramen tayo sa bakasyon hahaha",
    "I miss u bday gurl",
    "Thank you for inspiring me to be a better person everyday",
    "Anong wish mo for 2day?",
    "Ano fave cake mo?",
    "otanjoubi omedetou",
    "Nature trip tayo ha!",
    "Your flaws are perfect for the heart thats meant to love you.",
    "I know you'll achieve ur goals in life",
    "I always believe in you",
    "The world is so small compared to my love for you. kimmy",
    "I cant wait to see you again",
    "In case I dont tell you often enough, Im so grateful for all you bring to my life!",
    "Happy birthday and all the best to you in the year to come!",
    "Happy, happy birthday",
    "I hope you get to do something fun to celebrate!",
    "I absolutely adore you. Just FYI.",
    "I want you to know na you are a good person",
    "Hope today is filled with all your favorite guilty pleasures!",
    "You always matter to me. I hope you have a good day.",
    "Okay lang ba color combi nito? huhu sorry kung pangit color palette",
    "Sana matapos mo na mga plates mo! enjoy ur day",
    "Wish ko sana msarap tulog mo",
    "Here's to a year filled with new beginnings, exciting adventures, and lots of love. Happy Birthday!",
    "Wishing you a day filled with all your favorite things. Happy Birthday!",
    "Wala na ba talaga 2nd chance?",
    "Without a doubt, I am yours.",
    "Enjoy your day to the fullest!",
    "Ano ba ang mali sa akin?",
    "Happy birthday beautiful! I hope you have a wonderful day filled with joy and happiness.",
    "What are your 3 wishes?",
    "You are not getting older you are getting wiser.",
    "May your smile shine eternally as bright as it does now.",
    "The best decision I have made in this life is making a friend like you. Wish you a joyful Birthday. Stay happy and healthy always.",
    "I cant imagine living a life without you.",
    "May God bless you with lots of happiness!",
    "Sana ako na lang ulit.",
    "You have no idea the amount of happiness you brought into my life.",
    "Hindi mo na ba talaga ako mahal?",
    "I am always rooting for you",
    "I have no doubt that someday you will achieve all of your goals in life!",
  ]
  const textEl = document.querySelector(".TextMassage")
  textEl.textContent = messages[Math.floor( Math.random()*messages.length )]
})
